name: online-shopping

server:
  port: 8089
  servlet:
    context-path: /online-shopping

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hytech
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  check-config-location: true
  mapper-locations: classpath:mappers/*/*.xml

logging:
  level:
    tk.mybatis: DEBUG
    com.hytech.online.shopping: DEBUG
  path: /Users/zhaozehao/companyProject/logDir/hytech/online-shoppingLog

